version: '3.3'
services:
  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - springbankNet
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - $PWD/storage/mongo:/data/db
    networks:
      - springbankNet
  mysql_server:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "distibuted_txn"
    ports:
      - "3306:3306"
    volumes:
      - $PWD/mysql/volumes:/var/lib/mysql
    networks:
      - springbankNet

networks:
  springbankNet: