# ./docker/docker-compose.yml

version: '3.2'

services: 

  elasticsearch:
    container_name: elasticsearch_jtech
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment: 
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
      discovery.type: single-node
      xpath-security.enable: "true"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - internal
    restart: unless-stopped

  logstash:
    container_name: logstash_jtech
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:7.10.2
    ports: 
      - "5000:5000"
      - "9600:9600"
    environment: 
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_USER: elastic
      ELASTIC_PASSWORD: changeme
      XPACK_MONITORING_ELASTICSEARCH_USERNAME: elastic
      XPACK_MONITORING_ELASTICSEARCH_PASSWORD: changeme
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
    volumes: 
      - 'logstash:/log'
      - '$PWD/logstash/pipeline/logstash.conf:/conf/logstash.conf'
    command: logstash -f /conf/logstash.conf
    networks: 
      - internal
    restart: unless-stopped
    depends_on: 
      - elasticsearch

  kibana:
    container_name: kibana_001
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment: 
      ELASTICSEARCH_USERNAME: $ELASTIC_USER
      ELASTICSEARCH_PASSWORD: $ELASTIC_PASSWORD
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
    ports: 
      - "5601:5601"
    networks: 
      - internal
    restart: unless-stopped
    depends_on: 
      - elasticsearch
      - logstash


networks: 
  internal: 

volumes: 
  elasticsearch:
  logstash: