version: '3.3'
services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - doutorado
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - doutorado
  mysql_server:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "distibuted_txn"
    ports:
      - "3306:3306"
    volumes:
      - $PWD/mysql/volumes:/var/lib/mysql
    networks:
      - doutorado
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - $PWD/storage/mongo:/data/db
    networks:
      - doutorado

networks:
  doutorado:

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local