version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "users"
    ports:
      - "3306:3306"
    volumes:
      - /home/angelo.vicente/clients/docker-volumes/mysql/volumes:/var/lib/mysql
